import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app/app.dart';
import 'core/app_config.dart';
import 'core/notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (AppConfig.hasSupabase) {
    await Supabase.initialize(
      url: AppConfig.supabaseUrl,
      publishableKey: AppConfig.supabasePublishableKey,
    );
  }

  // Firebase is initialized from native configuration files on Android/iOS.
  // Web needs firebase_options.dart generated by FlutterFire.
  try {
    await Firebase.initializeApp();
    await NotificationService.initialize();
  } catch (_) {
    // Keep local/web demo startup possible before Firebase is configured.
  }

  runApp(const SilverHandsApp());
}
