create extension if not exists vector;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  user_type text,
  language text default 'English',
  location text,
  latitude double precision,
  longitude double precision,
  skills text[] default '{}',
  experience_years integer default 0,
  trusted_guide_name text,
  verified boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subtitle text,
  description text,
  business_name text not null,
  category text,
  price text,
  image_url text,
  skills text[] default '{}',
  latitude double precision,
  longitude double precision,
  demand_score integer default 10,
  seasonal_score integer default 10,
  verified boolean default false,
  sellers_required integer default 1,
  buyer_interested boolean default true,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.seller_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  skills text[] default '{}',
  location text,
  capacity_units integer default 0,
  reliability_score integer default 0,
  latitude double precision,
  longitude double precision,
  updated_at timestamptz default now()
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  opportunity_id uuid references public.opportunities(id) on delete cascade,
  interested boolean not null default false,
  created_at timestamptz default now(),
  unique(user_id, opportunity_id)
);

create table if not exists public.device_tokens (
  id bigint generated by default as identity primary key,
  token text unique not null,
  platform text not null,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  embedding vector(768),
  language text default 'English',
  created_at timestamptz default now()
);

create index if not exists knowledge_documents_embedding_idx
on public.knowledge_documents
using ivfflat (embedding vector_cosine_ops)
with (lists = 50);

create or replace function public.match_knowledge(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  title text,
  content text,
  similarity float
)
language sql stable
as $$
  select
    kd.id,
    kd.title,
    kd.content,
    1 - (kd.embedding <=> query_embedding) as similarity
  from public.knowledge_documents kd
  where kd.embedding is not null
    and 1 - (kd.embedding <=> query_embedding) >= match_threshold
  order by kd.embedding <=> query_embedding
  limit match_count;
$$;

alter table public.profiles enable row level security;
alter table public.seller_profiles enable row level security;
alter table public.matches enable row level security;
alter table public.device_tokens enable row level security;
alter table public.opportunities enable row level security;
alter table public.knowledge_documents enable row level security;

create policy "profiles own row" on public.profiles
for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "seller own row" on public.seller_profiles
for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "opportunities readable" on public.opportunities
for select using (is_active = true);

create policy "matches own rows" on public.matches
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "device token own rows" on public.device_tokens
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Product image bucket.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Seed opportunities.
insert into public.opportunities
(id, title, subtitle, description, business_name, category, price, image_url, skills, latitude, longitude, demand_score, seasonal_score, verified, sellers_required)
values
('11111111-1111-1111-1111-111111111111', 'Traditional Festival Gift Hampers', 'Bulk order for 120 hampers',
 'Create thoughtful festive gift hampers with homemade savouries and a warm personal touch.',
 'Anand Celebrations', 'Food', '₹8,000 – ₹12,000',
 'https://images.unsplash.com/photo-1605627079912-97c3810a11a4?auto=format&fit=crop&w=900&q=80',
 array['Traditional cooking','Packaging'], 13.0418,80.2341,15,10,true,4
),
('22222222-2222-2222-2222-222222222222', 'Fresh Home-style Tiffins', 'Lunch service for 20 people',
 'Healthy vegetarian lunches for a small office.',
 'Asha Office Hub', 'Food', '₹14,000 / month',
 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',
 array['Cooking','Meal prep'], 13.0067,80.2570,14,8,true,2
),
('33333333-3333-3333-3333-333333333333', 'Hindi Storytelling Club', 'Two evening sessions weekly',
 'Interactive Hindi storytelling sessions for children.',
 'Little Learners', 'Service', '₹6,000 / month',
 'https://images.unsplash.com/photo-1455885666463-9f76c3e2c1c1?auto=format&fit=crop&w=900&q=80',
 array['Storytelling','Teaching'], 13.0850,80.2101,12,7,true,1
)
on conflict do nothing;

insert into public.knowledge_documents(title, content, language)
values
('SilverHands Safety', 'SilverHands never asks a seller to share an Aadhaar number publicly. Verification should use a secure identity provider flow and only retain the minimum information required.', 'English'),
('Seller guidance', 'Sellers should confirm order quantity, deadline, payment terms and delivery responsibilities before accepting a bulk order.', 'English'),
('Trusted guide', 'A trusted family guide can help a senior citizen or homemaker navigate the app. The user should be able to remove access at any time.', 'English')
on conflict do nothing;

create policy "product images read"
on storage.objects for select
using (bucket_id = 'product-images');

create policy "product images authenticated upload"
on storage.objects for insert to authenticated
with check (bucket_id = 'product-images');

create policy "product images owner update"
on storage.objects for update to authenticated
using (bucket_id = 'product-images' and owner_id = auth.uid()::text)
with check (bucket_id = 'product-images' and owner_id = auth.uid()::text);
