-- SilverHands Family Guide support.
-- Run after 002_live_prototype.sql.

alter table public.opportunities
  add column if not exists owner_id uuid references auth.users(id) on delete cascade;

create table if not exists public.guide_links (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  guide_id uuid references auth.users(id) on delete set null,
  guide_name text,
  relationship text default 'Family member',
  invite_code text not null unique,
  status text not null default 'pending'
    check (status in ('pending','active','revoked','expired')),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guide_links_owner_idx on public.guide_links(owner_id);
create index if not exists guide_links_guide_idx on public.guide_links(guide_id);
create index if not exists opportunities_owner_idx on public.opportunities(owner_id);

alter table public.guide_links enable row level security;

drop policy if exists "owner manages guide links" on public.guide_links;
create policy "owner manages guide links"
on public.guide_links for all to authenticated
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "guide reads own links" on public.guide_links;
create policy "guide reads own links"
on public.guide_links for select to authenticated
using (auth.uid() = guide_id);

-- A guide can accept a code without knowing the owner's UUID.
create or replace function public.accept_guide_code(
  p_code text,
  p_guide_name text,
  p_relationship text default 'Family member'
)
returns public.guide_links
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.guide_links;
begin
  update public.guide_links
  set guide_id = auth.uid(),
      guide_name = nullif(trim(p_guide_name), ''),
      relationship = coalesce(nullif(trim(p_relationship), ''), 'Family member'),
      status = 'active',
      updated_at = now()
  where invite_code = trim(p_code)
    and status = 'pending'
    and expires_at > now()
  returning * into result;

  if result.id is null then
    raise exception 'Invalid or expired guide code';
  end if;

  return result;
end;
$$;

revoke all on function public.accept_guide_code(text,text,text) from public;
grant execute on function public.accept_guide_code(text,text,text) to authenticated;

create or replace function public.revoke_guide_link(p_link_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.guide_links
  set status = 'revoked', updated_at = now()
  where id = p_link_id and owner_id = auth.uid();
  return found;
end;
$$;

revoke all on function public.revoke_guide_link(uuid) from public;
grant execute on function public.revoke_guide_link(uuid) to authenticated;

-- Owner can see their own profile; an active guide can read it.
drop policy if exists "profiles guide read" on public.profiles;
create policy "profiles guide read"
on public.profiles for select to authenticated
using (
  auth.uid() = id
  or exists (
    select 1 from public.guide_links gl
    where gl.owner_id = profiles.id
      and gl.guide_id = auth.uid()
      and gl.status = 'active'
  )
);


drop policy if exists "opportunities owner write" on public.opportunities;
create policy "opportunities owner write"
on public.opportunities for all to authenticated
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

-- A guide can read the linked member's opportunities. Core profile updates
-- remain owner-only because the existing profiles write policy still requires
-- auth.uid() = id.
drop policy if exists "opportunities guide readable" on public.opportunities;
create policy "opportunities guide readable"
on public.opportunities for select to authenticated
using (
  is_active = true
  or exists (
    select 1 from public.guide_links gl
    where gl.owner_id = opportunities.owner_id
      and gl.guide_id = auth.uid()
      and gl.status = 'active'
  )
);

drop policy if exists "matches guide readable" on public.matches;
create policy "matches guide readable"
on public.matches for select to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1 from public.guide_links gl
    where gl.owner_id = matches.user_id
      and gl.guide_id = auth.uid()
      and gl.status = 'active'
  )
);

-- Helpful non-sensitive guide activity log.
create table if not exists public.guide_activity (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  guide_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

alter table public.guide_activity enable row level security;

drop policy if exists "guide activity linked read" on public.guide_activity;
create policy "guide activity linked read"
on public.guide_activity for select to authenticated
using (
  auth.uid() = guide_id
  or auth.uid() = owner_id
);

drop policy if exists "guide activity guide insert" on public.guide_activity;
create policy "guide activity guide insert"
on public.guide_activity for insert to authenticated
with check (
  auth.uid() = guide_id
  and exists (
    select 1 from public.guide_links gl
    where gl.owner_id = guide_activity.owner_id
      and gl.guide_id = auth.uid()
      and gl.status = 'active'
  )
);
